name: Test PAT Push

on:
  workflow_dispatch:

jobs:
  test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (no persist credentials)
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # 禁用默认 token（关键！）

      - name: Make dummy change
        run: echo "Test push on $(date)" >> test_push.md

      - name: Commit change
        run: |
          git config user.name "HAONANTAO"
          git config user.email "haonantao@example.com"
          git add test_push.md
          git commit -m "Test push commit" || echo "Nothing to commit"

      - name: Push change using PAT
        env:
          PAT: ${{ secrets.NOTIONSECRET }}
        run: |
          git remote set-url origin https://x-access-token:${PAT}@github.com/${{ github.repository }}.git
          git push origin main
