name: Test Git Push Permission

on:
  workflow_dispatch:

jobs:
  test-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Debug PAT token
        run: echo "PAT length: ${#PAT_TOKEN}"
        env:
          PAT_TOKEN: ${{ secrets.NOTIONSECRET }}

      - name: Make a test commit
        run: |
          echo "Test push at $(date)" >> test_push.md
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add test_push.md
          git commit -m "Test push from workflow"

      - name: Push changes
        env:
          PAT_TOKEN: ${{ secrets.NOTIONSECRET }}
        run: |
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git
          git push origin HEAD:main
