name: Test PAT Push

on:
  workflow_dispatch:

jobs:
  test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make dummy change
        run: echo "test push $(date)" >> test_push.md

      - name: Commit the change
        run: |
          git config user.name "HAONANTAO"
          git config user.email "your@email.com"
          git add test_push.md
          git commit -m "Test push from workflow" || echo "Nothing to commit"

      - name: Push to main using PAT
        env:
          TOKEN: ${{ secrets.NOTIONSECRET }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
          git push origin main
        shell: bash
