name: Test Git Push Permission

on:
  workflow_dispatch:

jobs:
  test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make a dummy change
        run: |
          echo "test push $(date)" >> test_push.md
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add test_push.md
          git commit -m "Test push from workflow" || echo "Nothing to commit"

      - name: Debug PAT token length
        run: echo "PAT length: ${#NOTIONSECRET}"
        env:
          PAT_TOKEN: ${{ secrets.NOTIONSECRET }}

      - name: Push changes using PAT
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.NOTIONSECRET }}@github.com/${{ github.repository }}.git
          git push origin HEAD:main
