name: Test Git Push Permission

on:
  workflow_dispatch:

jobs:
  test-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |
          echo "test push $(date)" >> test_push.md
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add test_push.md
          git commit -m "Test push from workflow"
          git remote set-url origin https://x-access-token:${{ secrets.FORNOTION }}@github.com/${{ github.repository }}.git
          git push origin main
