name: Notion Notes Sync

# 触发条件：
# - 每天 UTC 零点自动运行一次
# - 也支持手动触发 workflow_dispatch
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 第一步：检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 第二步：安装 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 第三步：安装依赖
      - name: Install dependencies
        run: npm install

      # 第四步：执行你的同步脚本（脚本路径请自行确认）
      - name: Run Notion sync script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
        run: node scripts/notion-sync.js

      # 第五步：配置 git，提交并推送变更
      - name: Commit & Push changes
        env:
          # 用你自己创建的 PAT 赋值给这个 secret 名 FORNOTION
          GITHUB_TOKEN: ${{ secrets.FORNOTION }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          # 添加所有变更
          git add .

          # 提交，如果没有变更则跳过报错
          git commit -m "Sync Notion notes $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"

          # 设置远程仓库地址，使用带 token 的 URL 进行推送
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}

          # 推送到 main 分支
          git push origin main
