name: Test Notion PAT Push

on:
  workflow_dispatch:  # 支持手动触发

jobs:
  test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make a dummy file change
        run: |
          echo "Test PAT push at $(date)" >> notion_pat_test.md
          git config user.name "GitHub Action Bot"
          git config user.email "action@github.com"
          git add notion_pat_test.md
          git commit -m "Test commit using NOTIONSECRET" || echo "Nothing to commit"

      - name: Debug PAT token length
        run: echo "Token length: ${#TOKEN}"
        env:
          TOKEN: ${{ secrets.NOTIONSECRET }}

      - name: Push to repo using NOTIONSECRET
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.NOTIONSECRET }}@github.com/${{ github.repository }}.git
          git push origin HEAD:main
